In [1]:
import pandas as pd

# Importing csv file

In [2]:
df = pd.read_csv("placement.csv")

In [3]:
df

    Unnamed: 0  cgpa     iq  placement
0            0   6.8  123.0          1
1            1   5.9  106.0          0
2            2   5.3  121.0          0
3            3   7.4  132.0          1
4            4   5.8  142.0          0
..         ...   ...    ...        ...
95          95   4.3  200.0          0
96          96   4.4   42.0          0
97          97   6.7  182.0          1
98          98   6.3  103.0          1
99          99   6.2  113.0          1

[100 rows x 4 columns]

# Importing csv data from a server via url

In [73]:
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/google/dspl/master/samples/google/canonical/countries.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

    country   latitude  longitude                  name
0        AD  42.546245   1.601554               Andorra
1        AE  23.424076  53.847818  United Arab Emirates
2        AF  33.939110  67.709953           Afghanistan
3        AG  17.060816 -61.796428   Antigua and Barbuda
4        AI  18.220554 -63.068615              Anguilla
..      ...        ...        ...                   ...
240      YE  15.552727  48.516388                 Yemen
241      YT -12.827500  45.166244               Mayotte
242      ZA -30.559482  22.937506          South Africa
243      ZM -13.133897  27.849332                Zambia
244      ZW -19.015438  29.154857              Zimbabwe

[245 rows x 4 columns]

# sep parameter(also for tsv) and giving custom column names/headers

In [67]:
df = pd.read_csv("file.tsv", sep='\t', names=['sr no', 'region code', 'no of aircrafts', 'population'])

In [68]:
df

        sr no  region code  no of aircrafts  population
0           0           50                5   881250949
1           0          172                5   881250949
2           0          133                1   881250949
3         196          242                3   881250949
4         186          302                3   891717742
...       ...          ...              ...         ...
99998     880          476                3   880175444
99999     716          204                5   879795543
100000    276         1090                1   874795795
100001     13          225                2   882399156
100002     12          203                3   879959583

[100003 rows x 4 columns]

# index_col parameter(custom select a column as index)

In [18]:
pd.read_csv('placement.csv', index_col='Unnamed: 0')

    cgpa     iq  placement
0    6.8  123.0          1
1    5.9  106.0          0
2    5.3  121.0          0
3    7.4  132.0          1
4    5.8  142.0          0
..   ...    ...        ...
95   4.3  200.0          0
96   4.4   42.0          0
97   6.7  182.0          1
98   6.3  103.0          1
99   6.2  113.0          1

[100 rows x 3 columns]

# Header parameter (custom set a row as header, use: when header itself becomes a data and u wanna change it)

In [21]:
pd.read_csv('placement.csv', header=1)

     0  6.8  123.0  1
0    1  5.9  106.0  0
1    2  5.3  121.0  0
2    3  7.4  132.0  1
3    4  5.8  142.0  0
4    5  7.1   48.0  1
..  ..  ...    ... ..
94  95  4.3  200.0  0
95  96  4.4   42.0  0
96  97  6.7  182.0  1
97  98  6.3  103.0  1
98  99  6.2  113.0  1

[99 rows x 4 columns]

# usecols parameter (to importe specific columns only)

In [24]:
pd.read_csv('placement.csv', usecols=['cgpa','placement'])

    cgpa  placement
0    6.8          1
1    5.9          0
2    5.3          0
3    7.4          1
4    5.8          0
..   ...        ...
95   4.3          0
96   4.4          0
97   6.7          1
98   6.3          1
99   6.2          1

[100 rows x 2 columns]

# skiprows/nrows parameter(used to skip selected rows, here 0 is header)

In [35]:
pd.read_csv("placement.csv", skiprows=[1,3])

    Unnamed: 0  cgpa     iq  placement
0            1   5.9  106.0          0
1            3   7.4  132.0          1
2            4   5.8  142.0          0
3            5   7.1   48.0          1
4            6   5.7  143.0          0
..         ...   ...    ...        ...
93          95   4.3  200.0          0
94          96   4.4   42.0          0
95          97   6.7  182.0          1
96          98   6.3  103.0          1
97          99   6.2  113.0          1

[98 rows x 4 columns]

# nrows parameter (limits the number of rows loaded into the memory)

In [37]:
df = pd.read_csv('placement.csv', nrows=20)

In [38]:
df

    Unnamed: 0  cgpa     iq  placement
0            0   6.8  123.0          1
1            1   5.9  106.0          0
2            2   5.3  121.0          0
3            3   7.4  132.0          1
4            4   5.8  142.0          0
5            5   7.1   48.0          1
6            6   5.7  143.0          0
7            7   5.0   63.0          0
8            8   6.1  156.0          0
9            9   5.1   66.0          0
10          10   6.0   45.0          1
11          11   6.9  138.0          1
12          12   5.4  139.0          0
13          13   6.4  116.0          1
14          14   6.1  103.0          0
15          15   5.1  176.0          0
16          16   5.2  224.0          0
17          17   3.3  183.0          0
18          18   4.0  100.0          0
19          19   5.2  132.0          0

# Encoding parameter

In [45]:
df = pd.read_csv("zomato.csv", encoding="latin-1") #if default encoding isnt working u ca change it

# Skip bad lines

In [ ]:
Used when incorrect amount of data is given which doesnt match the number of columns. ex: 9 values for 8 columns = ERROR

In [51]:
pd.read_csv("zomato.csv", on_bad_lines="skip").head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51712,https://www.zomato.com/bangalore/best-brews-fo...,"Four Points by Sheraton Bengaluru, 43/3, White...",Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,27,080 40301477,Whitefield,Bar,NaN,Continental,"1,500","[('Rated 5.0', ""RATED\n Food and service are ...",[],Pubs and bars,Whitefield
51713,https://www.zomato.com/bangalore/vinod-bar-and...,"Number 10, Garudachar Palya, Mahadevapura, Whi...",Vinod Bar And Restaurant,No,No,NaN,0,+91 8197675843,Whitefield,Bar,NaN,Finger Food,600,[],[],Pubs and bars,Whitefield
51714,https://www.zomato.com/bangalore/plunge-sherat...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,0,NaN,Whitefield,Bar,NaN,Finger Food,"2,000",[],[],Pubs and bars,Whitefield
51715,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500","[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield
51716,https://www.zomato.com/bangalore/the-nest-the-...,"ITPL Main Road, KIADB Export Promotion Industr...",The Nest - The Den Bengaluru,No,No,3.4 /5,13,+91 8071117272,"ITPL Main Road, Whitefield","Bar, Casual Dining",NaN,"Finger Food, North Indian, Continental","1,500","[('Rated 5.0', 'RATED\n Great ambience , look...",[],Pubs and bars,Whitefield

# dtypes parameter

In [ ]:
data is given in float unnecessarily like 1.0, 0.0 it takes more memory so we shld convert it to int using: dtype={'column_name':int}

In [59]:
pd.read_csv("placement.csv", dtype={"iq":int})

    Unnamed: 0  cgpa   iq  placement
0            0   6.8  123          1
1            1   5.9  106          0
2            2   5.3  121          0
3            3   7.4  132          1
4            4   5.8  142          0
..         ...   ...  ...        ...
95          95   4.3  200          0
96          96   4.4   42          0
97          97   6.7  182          1
98          98   6.3  103          1
99          99   6.2  113          1

[100 rows x 4 columns]

# Handling dates

parse a perticular column as date: parse_dates=['column_with_dates']

In [62]:
pd.read_csv("Health_AnimalBites.csv", ).info() #before

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9003 entries, 0 to 9002
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   bite_date          8686 non-null   object
 1   SpeciesIDDesc      8885 non-null   object
 2   BreedIDDesc        3759 non-null   object
 3   GenderIDDesc       6477 non-null   object
 4   color              6426 non-null   object
 5   vaccination_yrs    3738 non-null   float64
 6   vaccination_date   4115 non-null   object
 7   victim_zip         7165 non-null   object
 8   AdvIssuedYNDesc    2565 non-null   object
 9   WhereBittenIDDesc  8387 non-null   object
 10  quarantine_date    2020 non-null   object
 11  DispositionIDDesc  1535 non-null   object
 12  head_sent_date     395 non-null    object
 13  release_date       1445 non-null   object
 14  ResultsIDDesc      1543 non-null   object
dtypes: float64(1), object(14)
memory usage: 1.0+ MB

In [75]:
pd.read_csv("Health_AnimalBites.csv", parse_dates=["quarantine_date"]).info() #After

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9003 entries, 0 to 9002
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   bite_date          8686 non-null   object
 1   SpeciesIDDesc      8885 non-null   object
 2   BreedIDDesc        3759 non-null   object
 3   GenderIDDesc       6477 non-null   object
 4   color              6426 non-null   object
 5   vaccination_yrs    3738 non-null   float64
 6   vaccination_date   4115 non-null   object
 7   victim_zip         7165 non-null   object
 8   AdvIssuedYNDesc    2565 non-null   object
 9   WhereBittenIDDesc  8387 non-null   object
 10  quarantine_date    2020 non-null   datetime64[ns]
 11  DispositionIDDesc  1535 non-null   object
 12  head_sent_date     395 non-null    object
 13  release_date       1445 non-null   object
 14  ResultsIDDesc      1543 non-null   object
dtypes: datetime64[ns](1), float64(1), object(13)
memory usage: 1.0+ MB

In [65]:
pd.read_csv("Health_AnimalBites.csv")

,bite_date,SpeciesIDDesc,BreedIDDesc,GenderIDDesc,color,vaccination_yrs,vaccination_date,victim_zip,AdvIssuedYNDesc,WhereBittenIDDesc,quarantine_date,DispositionIDDesc,head_sent_date,release_date,ResultsIDDesc
0,1985-05-05 00:00:00,DOG,NaN,FEMALE,LIG. BROWN,1.0,1985-06-20 00:00:00,40229,NO,BODY,1985-05-05 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
1,1986-02-12 00:00:00,DOG,NaN,UNKNOWN,BRO & BLA,NaN,NaN,40218,NO,BODY,1986-02-12 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
2,1987-05-07 00:00:00,DOG,NaN,UNKNOWN,NaN,NaN,NaN,40219,NO,BODY,1990-05-07 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
3,1988-10-02 00:00:00,DOG,NaN,MALE,BLA & BRO,NaN,NaN,NaN,NO,BODY,1990-10-02 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
4,1989-08-29 00:00:00,DOG,NaN,FEMALE,BLK-WHT,NaN,NaN,NaN,NO,BODY,NaN,UNKNOWN,NaN,NaN,UNKNOWN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8998,2017-09-05 00:00:00,DOG,NaN,NaN,NaN,NaN,NaN,40243,NaN,UNKNOWN,NaN,NaN,NaN,NaN,NaN
8999,2017-09-07 00:00:00,DOG,POMERANIAN,MALE,RED,NaN,NaN,40204,NaN,HEAD,NaN,NaN,NaN,NaN,NaN
9000,2017-09-07 00:00:00,DOG,LABRADOR RETRIV,MALE,BROWN,NaN,NaN,47130,NaN,UNKNOWN,NaN,NaN,NaN,NaN,NaN
9001,2017-09-07 00:00:00,DOG,LABRADOR RETRIV,FEMALE,BLK WHT,NaN,NaN,40229,NaN,BODY,NaN,NaN,NaN,NaN,NaN
9002,2017-09-07 00:00:00,DOG,BOXER,NaN,BRN BLK,NaN,NaN,40229,NaN,BODY,NaN,NaN,NaN,NaN,NaN

currently not working as some non null values may contains random strings instead of date time

# converters

you can apply python functions to replace all the values of a column. EX: converters={'column_name':function_name}

### Function

In [84]:
def rename(GenderIDDesc):
    if GenderIDDesc == "FEMALE":
        return "Women 🚺"
    elif GenderIDDesc == "MALE":
        return "Man 🚹"
    else:
        return GenderIDDesc

In [85]:
rename("MALE")

'Man 🚹'

In [86]:
pd.read_csv("Health_AnimalBites.csv", converters={"GenderIDDesc":rename})

,bite_date,SpeciesIDDesc,BreedIDDesc,GenderIDDesc,color,vaccination_yrs,vaccination_date,victim_zip,AdvIssuedYNDesc,WhereBittenIDDesc,quarantine_date,DispositionIDDesc,head_sent_date,release_date,ResultsIDDesc
0,1985-05-05 00:00:00,DOG,NaN,Women 🚺,LIG. BROWN,1.0,1985-06-20 00:00:00,40229,NO,BODY,1985-05-05 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
1,1986-02-12 00:00:00,DOG,NaN,UNKNOWN,BRO & BLA,NaN,NaN,40218,NO,BODY,1986-02-12 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
2,1987-05-07 00:00:00,DOG,NaN,UNKNOWN,NaN,NaN,NaN,40219,NO,BODY,1990-05-07 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
3,1988-10-02 00:00:00,DOG,NaN,Man 🚹,BLA & BRO,NaN,NaN,NaN,NO,BODY,1990-10-02 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
4,1989-08-29 00:00:00,DOG,NaN,Women 🚺,BLK-WHT,NaN,NaN,NaN,NO,BODY,NaN,UNKNOWN,NaN,NaN,UNKNOWN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8998,2017-09-05 00:00:00,DOG,NaN,,NaN,NaN,NaN,40243,NaN,UNKNOWN,NaN,NaN,NaN,NaN,NaN
8999,2017-09-07 00:00:00,DOG,POMERANIAN,Man 🚹,RED,NaN,NaN,40204,NaN,HEAD,NaN,NaN,NaN,NaN,NaN
9000,2017-09-07 00:00:00,DOG,LABRADOR RETRIV,Man 🚹,BROWN,NaN,NaN,47130,NaN,UNKNOWN,NaN,NaN,NaN,NaN,NaN
9001,2017-09-07 00:00:00,DOG,LABRADOR RETRIV,Women 🚺,BLK WHT,NaN,NaN,40229,NaN,BODY,NaN,NaN,NaN,NaN,NaN
9002,2017-09-07 00:00:00,DOG,BOXER,,BRN BLK,NaN,NaN,40229,NaN,BODY,NaN,NaN,NaN,NaN,NaN

# na_values parameter

pandas by default considers blank values as NaN but sometimes instead of blank the values is -, etc. so we can use 'na_values' to define custom values as NaN. EX: na_values=['-',etc]

In [89]:
pd.read_csv("Health_AnimalBites.csv", na_values=["UNKNOWN"])

,bite_date,SpeciesIDDesc,BreedIDDesc,GenderIDDesc,color,vaccination_yrs,vaccination_date,victim_zip,AdvIssuedYNDesc,WhereBittenIDDesc,quarantine_date,DispositionIDDesc,head_sent_date,release_date,ResultsIDDesc
0,1985-05-05 00:00:00,DOG,NaN,FEMALE,LIG. BROWN,1.0,1985-06-20 00:00:00,40229,NO,BODY,1985-05-05 00:00:00,NaN,NaN,NaN,NaN
1,1986-02-12 00:00:00,DOG,NaN,NaN,BRO & BLA,NaN,NaN,40218,NO,BODY,1986-02-12 00:00:00,NaN,NaN,NaN,NaN
2,1987-05-07 00:00:00,DOG,NaN,NaN,NaN,NaN,NaN,40219,NO,BODY,1990-05-07 00:00:00,NaN,NaN,NaN,NaN
3,1988-10-02 00:00:00,DOG,NaN,MALE,BLA & BRO,NaN,NaN,NaN,NO,BODY,1990-10-02 00:00:00,NaN,NaN,NaN,NaN
4,1989-08-29 00:00:00,DOG,NaN,FEMALE,BLK-WHT,NaN,NaN,NaN,NO,BODY,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8998,2017-09-05 00:00:00,DOG,NaN,NaN,NaN,NaN,NaN,40243,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8999,2017-09-07 00:00:00,DOG,POMERANIAN,MALE,RED,NaN,NaN,40204,NaN,HEAD,NaN,NaN,NaN,NaN,NaN
9000,2017-09-07 00:00:00,DOG,LABRADOR RETRIV,MALE,BROWN,NaN,NaN,47130,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9001,2017-09-07 00:00:00,DOG,LABRADOR RETRIV,FEMALE,BLK WHT,NaN,NaN,40229,NaN,BODY,NaN,NaN,NaN,NaN,NaN
9002,2017-09-07 00:00:00,DOG,BOXER,NaN,BRN BLK,NaN,NaN,40229,NaN,BODY,NaN,NaN,NaN,NaN,NaN

# Loading a huge data set in chunks

In [96]:
chunks = pd.read_csv("Health_AnimalBites.csv", chunksize=2000)

In [97]:
for chunk in chunks:
    print(chunk.shape)

(2000, 15)
(2000, 15)
(2000, 15)
(2000, 15)
(1003, 15)