In [3]:
import pandas as pd
import numpy as np

In [6]:
date = pd.read_csv('../Data sets/orders.csv')
time = pd.read_csv('../Data sets/messages.csv')

In [9]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [10]:
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   str
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), str(1)
memory usage: 41.1 KB

In [11]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   str
 1   msg     1000 non-null   str
dtypes: str(2)
memory usage: 118.7 KB

#### cols are not in dateTIme dtype

In [12]:
date['date'] = pd.to_datetime(date['date'])

In [13]:
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[us]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[us](1), int64(3)
memory usage: 31.4 KB

## Extract year

In [14]:
date['year'] = date['date'].dt.year

In [16]:
date.head()

        date  product_id  city_id  orders  year
0 2019-12-10        5628       25       3  2019
1 2018-08-15        3646       14     157  2018
2 2018-10-23        1859       25       1  2018
3 2019-08-17        7292       25       1  2019
4 2019-01-06        4344       25       3  2019

## Extract month

In [17]:
date['month'] = date['date'].dt.month

In [18]:
date.head()

        date  product_id  city_id  orders  year  month
0 2019-12-10        5628       25       3  2019     12
1 2018-08-15        3646       14     157  2018      8
2 2018-10-23        1859       25       1  2018     10
3 2019-08-17        7292       25       1  2019      8
4 2019-01-06        4344       25       3  2019      1

### If you want name of the month

In [23]:
date['month_name'] = date['date'].dt.month_name()

In [24]:
date.head()

        date  product_id  city_id  orders  year  month month_name
0 2019-12-10        5628       25       3  2019     12   December
1 2018-08-15        3646       14     157  2018      8     August
2 2018-10-23        1859       25       1  2018     10    October
3 2019-08-17        7292       25       1  2019      8     August
4 2019-01-06        4344       25       3  2019      1    January

## Extract day

In [26]:
date['day'] = date['date'].dt.day
date.head()

        date  product_id  city_id  orders  year  month month_name  day
0 2019-12-10        5628       25       3  2019     12   December   10
1 2018-08-15        3646       14     157  2018      8     August   15
2 2018-10-23        1859       25       1  2018     10    October   23
3 2019-08-17        7292       25       1  2019      8     August   17
4 2019-01-06        4344       25       3  2019      1    January    6

### Extrat day of week; can be usefull for finding weekend

In [29]:
date['day_of_week'] = date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,year,month,month_name,day,day_of_week
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

## extract name of day of the week

In [31]:
date['day_name'] = date['date'].dt.day_name()
date.head()

,date,product_id,city_id,orders,year,month,month_name,day,day_of_week,day_name
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday

## finding if the day is weekend or not?

In [34]:
date['is_weekend'] = np.where(date['day_name'].isin(['Saturday','Sunday']), 1,0)

date.head()

,date,product_id,city_id,orders,year,month,month_name,day,day_of_week,day_name,is_weekend
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1

## week of the year

In [38]:
date["week"] = date['date'].dt.isocalendar().week
date.head()

,date,product_id,city_id,orders,year,month,month_name,day,day_of_week,day_name,is_weekend,week
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1

### Quarter

In [40]:
date['quarter'] = date['date'].dt.quarter
date.head()

,date,product_id,city_id,orders,year,month,month_name,day,day_of_week,day_name,is_weekend,week,quarter
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1

### Find sem

In [46]:
date['sem'] = np.where(date['quarter'].isin([1,2]), 1,2)
date.head()

,date,product_id,city_id,orders,year,month,month_name,day,day_of_week,day_name,is_weekend,week,quarter,sem
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1,1

# Extract time elapsed between two dates

In [60]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 6, 27, 14, 29, 0, 101185)

### Full elapsed

In [62]:
today - date['date']

0     2391 days 14:29:00.101185
1     2873 days 14:29:00.101185
2     2804 days 14:29:00.101185
3     2506 days 14:29:00.101185
4     2729 days 14:29:00.101185
                 ...
995   2819 days 14:29:00.101185
996   2760 days 14:29:00.101185
997   2608 days 14:29:00.101185
998   2673 days 14:29:00.101185
999   2447 days 14:29:00.101185
Name: date, Length: 1000, dtype: timedelta64[us]

### Only day

In [66]:
(today - date['date']).dt.days

0      2391
1      2873
2      2804
3      2506
4      2729
       ...
995    2819
996    2760
997    2608
998    2673
999    2447
Name: date, Length: 1000, dtype: int64

### Months passed

In [75]:
np.round((today - date['date']).dt.days / 30) #assuming each month has 30 days

0      80.0
1      96.0
2      93.0
3      84.0
4      91.0
       ...
995    94.0
996    92.0
997    87.0
998    89.0
999    82.0
Name: date, Length: 1000, dtype: float64

# **TIME**

In [78]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   str
 1   msg     1000 non-null   str
dtypes: str(2)
memory usage: 118.7 KB

In [79]:
time['date'] = pd.to_datetime(time['date'])

In [81]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[us]
 1   msg     1000 non-null   str
dtypes: datetime64[us](1), str(1)
memory usage: 100.1 KB

In [82]:
time.head()

                 date                                                msg
0 2013-12-15 00:50:00                           ищу на сегодня мужика 37
1 2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2 2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3 2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4 2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

## extract hours, minutes, seconds

In [86]:
time['Hour'] = time['date'].dt.hour
time['Minute'] = time['date'].dt.minute
time['Second'] = time['date'].dt.second

time.sample(10)

,date,msg,Hour,Minute,Second
295,2013-01-04 01:45:00,ПООБЩАЮСЬ С ДЕВУШКОЙ.063 413 86 95.ЗАДЕРЖИ. ...,1,45,0
391,2014-10-27 00:04:00,Парни давайте познакомимся,0,4,0
115,2012-07-31 00:47:00,П 29.Позн.с красивой и не глупой!(смс)066 787 ...,0,47,0
339,2013-07-16 01:51:00,красивая Д ищет умного М,1,51,0
606,2014-09-27 00:44:00,.М43.СИМПТ.БЕЗ.В/П.ДЛЯ.СТРОЙН.Д/Ж.БЕЗ.КОМПЛЕКС...,0,44,0
704,2014-02-12 02:00:00,Хочу шампанского фруктов и последствий!Вика,2,0,0
310,2012-09-24 23:49:00,парень 29 ищет девушку 0931035091 днепродзержинск,23,49,0
268,2013-10-16 00:35:00,я пар. мне 18 ищу девушку,0,35,0
474,2014-09-22 23:36:00,М55.ищу.д.ж.и.о.ласкаю.можн.замуж.неч.вст.,23,36,0
653,2013-11-04 00:58:00,юноша который п 25 номерок напиши,0,58,0

## Extract only time from date and time

In [87]:
time['time'] = time['date'].dt.time
time.head()

,date,msg,Hour,Minute,Second,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

## time difference

In [88]:
today - time['date']

0     4577 days 13:39:00.101185
1     4441 days 14:49:00.101185
2     4927 days 14:08:00.101185
3     4229 days 13:58:00.101185
4     4626 days 15:18:00.101185
                 ...
995   5216 days 13:39:00.101185
996   4537 days 15:15:00.101185
997   5002 days 14:52:00.101185
998   5118 days 14:55:00.101185
999   4390 days 15:04:00.101185
Name: date, Length: 1000, dtype: timedelta64[us]

### In seconds

In [98]:
(today - time['date'])/np.timedelta64(1,'s')

0      3.955019e+08
1      3.837557e+08
2      4.257437e+08
3      3.654359e+08
4      3.997415e+08
           ...
995    4.507115e+08
996    3.920517e+08
997    4.322263e+08
998    4.422489e+08
999    3.793502e+08
Name: date, Length: 1000, dtype: float64

In [99]:
(today - time['date']).dt.days*(24*60*60)

0      395452800
1      383702400
2      425692800
3      365385600
4      399686400
         ...
995    450662400
996    391996800
997    432172800
998    442195200
999    379296000
Name: date, Length: 1000, dtype: int64

### in minutes

In [100]:
(today - time['date'])/np.timedelta64(1,'m')

0      6.591699e+06
1      6.395929e+06
2      7.095728e+06
3      6.090598e+06
4      6.662358e+06
           ...
995    7.511859e+06
996    6.534195e+06
997    7.203772e+06
998    7.370815e+06
999    6.322504e+06
Name: date, Length: 1000, dtype: float64

In [101]:
(today - time['date']).dt.days*(24*60)

0      6590880
1      6395040
2      7094880
3      6089760
4      6661440
        ...
995    7511040
996    6533280
997    7202880
998    7369920
999    6321600
Name: date, Length: 1000, dtype: int64

### in hours

In [104]:
(today - time['date'])/np.timedelta64(1,'h')

0      109861.650028
1      106598.816695
2      118262.133361
3      101509.966695
4      111039.300028
           ...
995    125197.650028
996    108903.250028
997    120062.866695
998    122846.916695
999    105375.066695
Name: date, Length: 1000, dtype: float64

In [105]:
(today - time['date']).dt.days*(24)

0      109848
1      106584
2      118248
3      101496
4      111024
        ...
995    125184
996    108888
997    120048
998    122832
999    105360
Name: date, Length: 1000, dtype: int64